---
- name: test playbook
  hosts: all
  tasks:
  - name: Look up the VM called test_vm1 in the inventory
    register: search_result
    vmware.vmware_rest.vcenter_vm_info:
      filter_names:
      - test_vm1

  - name: Collect information about a specific VM
    vmware.vmware_rest.vcenter_vm_info:
      vm: '{{ search_result.value[0].vm }}'
    register: test_vm1_info

  - name: Get guest identity information
    vmware.vmware_rest.vcenter_vm_guest_identity_info:
      vm: '{{ test_vm1_info.id }}'
    register: _result

  - debug: var=test_vm1_info
